{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/FlowContainer"]},{"title":"Protocols","identifiers":["doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/NavigationBindingDelegate"]},{"title":"Extended Modules","identifiers":["doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/UIKit"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[[]]},"variants":[{"paths":["\/documentation\/flowcontainers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/flowcontainers"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"module","roleHeading":"Framework","title":"FlowContainers","role":"collection","modules":[{"name":"FlowContainers"}],"externalID":"FlowContainers"},"references":{"doc://com.peteschuette.FlowContainers/documentation/FlowContainers/FlowContainersVersionNumber":{"type":"topic","identifier":"doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/FlowContainersVersionNumber","abstract":[{"type":"text","text":"Project version number for FlowContainers."}],"title":"FlowContainersVersionNumber","fragments":[{"kind":"identifier","text":"FlowContainersVersionNumber"}],"kind":"symbol","url":"\/documentation\/flowcontainers\/flowcontainersversionnumber","role":"symbol"},"doc://com.peteschuette.FlowContainers/documentation/FlowContainers/UIKit":{"type":"topic","url":"\/documentation\/flowcontainers\/uikit","kind":"symbol","identifier":"doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/UIKit","title":"UIKit","role":"collection","abstract":[]},"doc://com.peteschuette.FlowContainers/documentation/FlowContainers/NavigationBindingDelegate":{"abstract":[{"text":"Interface for an object which acts as a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/FlowContainer"},{"type":"text","text":"‘s delegate when binding and unbinding from it’s "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/UIKit\/UINavigationController"}],"url":"\/documentation\/flowcontainers\/navigationbindingdelegate","role":"symbol","navigatorTitle":[{"text":"NavigationBindingDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationBindingDelegate"}],"type":"topic","title":"NavigationBindingDelegate","kind":"symbol","identifier":"doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/NavigationBindingDelegate"},"doc://com.peteschuette.FlowContainers/documentation/FlowContainers":{"type":"topic","url":"\/documentation\/flowcontainers","kind":"symbol","identifier":"doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers","title":"FlowContainers","role":"collection","abstract":[]},"doc://com.peteschuette.FlowContainers/documentation/FlowContainers/UIKit/UIViewController":{"type":"topic","url":"\/documentation\/flowcontainers\/uikit\/uiviewcontroller","fragments":[{"kind":"keyword","text":"extension"},{"text":" ","kind":"text"},{"text":"UIViewController","kind":"identifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"kind":"symbol","identifier":"doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/UIKit\/UIViewController","navigatorTitle":[{"kind":"identifier","text":"UIViewController"}],"title":"UIViewController","role":"symbol","abstract":[]},"doc://com.peteschuette.FlowContainers/documentation/FlowContainers/FlowContainersVersionString":{"role":"symbol","url":"\/documentation\/flowcontainers\/flowcontainersversionstring","identifier":"doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/FlowContainersVersionString","title":"FlowContainersVersionString","abstract":[{"type":"text","text":"Project version string for FlowContainers."}],"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"FlowContainersVersionString"}]},"doc://com.peteschuette.FlowContainers/documentation/FlowContainers/FlowContainer":{"title":"FlowContainer","abstract":[{"type":"text","text":"Base class for a container object which bundles a collection of "},{"identifier":"doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/UIKit\/UIViewController","type":"reference","isActive":true},{"type":"text","text":"s together to produce a unified experience or composed result"}],"identifier":"doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/FlowContainer","url":"\/documentation\/flowcontainers\/flowcontainer","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlowContainer"}],"navigatorTitle":[{"text":"FlowContainer","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.peteschuette.FlowContainers/documentation/FlowContainers/UIKit/UINavigationController":{"title":"UINavigationController","abstract":[],"identifier":"doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/UIKit\/UINavigationController","url":"\/documentation\/flowcontainers\/uikit\/uinavigationcontroller","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController"}],"navigatorTitle":[{"kind":"identifier","text":"UINavigationController"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/FlowContainersVersionNumber","doc:\/\/com.peteschuette.FlowContainers\/documentation\/FlowContainers\/FlowContainersVersionString"],"title":"Variables"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}